# Generated by Django 6.0.4 on 2026-04-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rareza', models.IntegerField(choices=[(4, '4 estrellas'), (5, '5 estrellas')])),
                ('elemento', models.CharField(choices=[('Anemo', 'Anemo'), ('Geo', 'Geo'), ('Electro', 'Electro'), ('Pyro', 'Pyro'), ('Hydro', 'Hydro'), ('Cryo', 'Cryo'), ('Dendro', 'Dendro')], max_length=100)),
                ('tipo_arma', models.CharField(max_length=20)),
                ('lore', models.TextField()),
                ('diseno_imagen', models.ImageField(upload_to='personajes/disenos/')),
                ('enka_api_id', models.IntegerField(help_text='ID para conectar con Enkanetwork', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arma', models.CharField(max_length=100)),
                ('set_artefactos', models.CharField(max_length=200)),
                ('stats_principales', models.TextField(help_text='Reloj ATQ%, Caliz Daño Elemental, Corona Daño Critico')),
                ('personaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='wiki.personaje')),
            ],
        ),
    ]
