# Generated by Django 6.0.4 on 2026-04-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='region',
            field=models.CharField(choices=[('Mondstadt', 'Mondstadt'), ('Liyue', 'Liyue'), ('Inazuma', 'Inazuma'), ('Sumeru', 'Sumeru'), ('Fontaine', 'Fontaine'), ('Natlan', 'Natlan'), ('Snezhnaya', 'Snezhnaya')], default='Mondstadt', max_length=20),
        ),
        migrations.AddField(
            model_name='personaje',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='tipo_arma',
            field=models.CharField(choices=[('Espada', 'Espada ligera'), ('Mandoble', 'Mandoble'), ('Lanza', 'Lanza'), ('Arco', 'Arco'), ('Catalizador', 'Catalizador')], default='Espada', max_length=20),
        ),
    ]
