# Generated by Django 6.0.4 on 2026-04-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_personaje_region_personaje_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rareza', models.IntegerField(default=4)),
                ('tipo', models.CharField(choices=[('Espada', 'Espada ligera'), ('Mandoble', 'Mandoble'), ('Lanza', 'Lanza'), ('Arco', 'Arco'), ('Catalizador', 'Catalizador')], max_length=20)),
                ('ataque_base', models.IntegerField()),
                ('substat_tipo', models.CharField(help_text='Ej: Daño Crítico, ATQ %', max_length=50)),
                ('substat_valor', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='armas/')),
                ('pasiva_nombre', models.CharField(blank=True, max_length=100)),
                ('pasiva_descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='enka_api_id',
        ),
    ]
