# Generated by Django 6.0.4 on 2026-04-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_arma_remove_personaje_enka_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='arma',
        ),
        migrations.AddField(
            model_name='build',
            name='arma_recomendada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wiki.arma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='explicacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='build',
            name='mejor_opcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='build',
            name='personaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='wiki.personaje'),
        ),
        migrations.AlterField(
            model_name='build',
            name='set_artefactos',
            field=models.CharField(help_text='Ej: 4 piezas de Sombra Verde Esmeralda', max_length=200),
        ),
        migrations.AlterField(
            model_name='build',
            name='stats_principales',
            field=models.CharField(help_text='Ej: ATQ% / Pyro / Crítico', max_length=255),
        ),
    ]
