# Generated by Django 6.0.4 on 2026-04-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='cta_texto',
            field=models.CharField(blank=True, help_text='Ej: Ver más, Descargar, Participar', max_length=50),
        ),
        migrations.AddField(
            model_name='novedad',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción corta del banner'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='link',
            field=models.URLField(blank=True, help_text='URL a donde llevará el click del banner'),
        ),
    ]
