# Generated by Django 6.0.4 on 2026-05-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('Ascensión', 'Ascensión'), ('Talento', 'Talento'), ('Mundo', 'Mundo'), ('Evento', 'Evento'), ('Otros', 'Otros')], default='Otros', max_length=30)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='materiales/')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_materials', to='wiki.build')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.material')),
            ],
            options={
                'unique_together': {('build', 'material')},
            },
        ),
        migrations.AddField(
            model_name='build',
            name='materiales',
            field=models.ManyToManyField(blank=True, related_name='builds', through='wiki.BuildMaterial', to='wiki.material'),
        ),
    ]
