# Generated by Django 6.0.4 on 2026-05-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_material_buildmaterial_build_materiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='materiales',
        ),
        migrations.DeleteModel(
            name='BuildMaterial',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
