# Generated by Django 6.0.4 on 2026-05-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_remove_build_materiales_delete_buildmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='diseno_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='personajes/disenos/'),
        ),
    ]
