# Generated by Django 6.0.4 on 2026-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_personaje_diseno_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='icono_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='personajes/icons/'),
        ),
    ]
