# Generated by Django 6.0.4 on 2026-05-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_personaje_icono_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['-mejor_opcion', 'categoria']},
        ),
        migrations.AddField(
            model_name='build',
            name='categoria',
            field=models.CharField(choices=[('DPS', 'DPS Principal'), ('SUB_DPS', 'Sub-DPS'), ('SOPORTE', 'Soporte'), ('CURATIVO', 'Curativo')], default='DPS', max_length=20),
        ),
        migrations.CreateModel(
            name='TeamComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('sinergia_description', models.TextField(help_text='Explicar por qué funcionan bien juntos')),
                ('dificultad', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Media'), (3, 'Difícil')], default=2)),
                ('curativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_como_curativo', to='wiki.personaje')),
                ('dps_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_como_dps', to='wiki.personaje')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_como_soporte', to='wiki.personaje')),
                ('sub_dps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_como_subdps', to='wiki.personaje')),
            ],
            options={
                'ordering': ['-dificultad'],
            },
        ),
    ]
