version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: genshin_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=genshin_wiki
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: genshin_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=clave_secreta_local_docker_12345
      - DATABASE_URL=postgres://postgres:postgres@db:5432/genshin_wiki
    depends_on:
      - db

volumes:
  postgres_data: